spring:
    # servlet config
    servlet:
      multipart:
        max-file-size: 100MB
        max-request-size: 100MB

    # database config
    datasource:
        url: jdbc:mysql://t4coach42.p.ssafy.io:3307/gitchecker?useSSL=false&serverTimezone=Asia/Seoul&useLegacyDatetimeCode=false&characterEncoding=UTF-8
        username: root
        password: coach
    # jpa config
    jpa:
        show-sql: true
        database-platform: org.hibernate.dialect.MySQL8Dialect
        hibernate:
            ddl-auto: create